# Generated by Django 2.2 on 2021-07-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdAppKPiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.CharField(max_length=100)),
                ('elapsed', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('responseCode', models.CharField(max_length=100)),
                ('responseMessage', models.CharField(max_length=100)),
                ('threadName', models.CharField(max_length=100)),
                ('dataType', models.CharField(max_length=100)),
                ('success', models.CharField(max_length=100)),
                ('failureMessage', models.CharField(max_length=100)),
                ('bytes', models.CharField(max_length=100)),
                ('sentBytes', models.CharField(max_length=100)),
                ('grpThreads', models.CharField(max_length=100)),
                ('allThreads', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=100)),
                ('Latency', models.CharField(max_length=100)),
                ('IdleTime', models.CharField(max_length=100)),
                ('Connect', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfresults',
            },
        ),
    ]
